// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/mx/config.proto

package mx

import (
	protocol "github.com/v2fly/v2ray-core/v5/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cuenta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cuenta) Reset() {
	*x = Cuenta{}
	mi := &file_proxy_mx_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cuenta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cuenta) ProtoMessage() {}

func (x *Cuenta) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mx_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cuenta.ProtoReflect.Descriptor instead.
func (*Cuenta) Descriptor() ([]byte, []int) {
	return file_proxy_mx_config_proto_rawDescGZIP(), []int{0}
}

func (x *Cuenta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfiguracionCliente struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Vnext         []*protocol.ServerEndpoint `protobuf:"bytes,1,rep,name=vnext,proto3" json:"vnext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfiguracionCliente) Reset() {
	*x = ConfiguracionCliente{}
	mi := &file_proxy_mx_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfiguracionCliente) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfiguracionCliente) ProtoMessage() {}

func (x *ConfiguracionCliente) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mx_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfiguracionCliente.ProtoReflect.Descriptor instead.
func (*ConfiguracionCliente) Descriptor() ([]byte, []int) {
	return file_proxy_mx_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfiguracionCliente) GetVnext() []*protocol.ServerEndpoint {
	if x != nil {
		return x.Vnext
	}
	return nil
}

type ConfiguracionServidor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfiguracionServidor) Reset() {
	*x = ConfiguracionServidor{}
	mi := &file_proxy_mx_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfiguracionServidor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfiguracionServidor) ProtoMessage() {}

func (x *ConfiguracionServidor) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mx_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfiguracionServidor.ProtoReflect.Descriptor instead.
func (*ConfiguracionServidor) Descriptor() ([]byte, []int) {
	return file_proxy_mx_config_proto_rawDescGZIP(), []int{2}
}

func (x *ConfiguracionServidor) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_proxy_mx_config_proto protoreflect.FileDescriptor

const file_proxy_mx_config_proto_rawDesc = "" +
	"\n" +
	"\x15proxy/mx/config.proto\x12\x13v2ray.core.proxy.mx\x1a!common/protocol/server_spec.proto\x1a\x1acommon/protocol/user.proto\"\x18\n" +
	"\x06Cuenta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x14ConfiguracionCliente\x12@\n" +
	"\x05vnext\x18\x01 \x03(\v2*.v2ray.core.common.protocol.ServerEndpointR\x05vnext\"O\n" +
	"\x15ConfiguracionServidor\x126\n" +
	"\x05users\x18\x01 \x03(\v2 .v2ray.core.common.protocol.UserR\x05usersBZ\n" +
	"\x17com.v2ray.core.proxy.mxP\x01Z'github.com/v2fly/v2ray-core/v5/proxy/mx\xaa\x02\x13V2Ray.Core.Proxy.Mxb\x06proto3"

var (
	file_proxy_mx_config_proto_rawDescOnce sync.Once
	file_proxy_mx_config_proto_rawDescData []byte
)

func file_proxy_mx_config_proto_rawDescGZIP() []byte {
	file_proxy_mx_config_proto_rawDescOnce.Do(func() {
		file_proxy_mx_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_mx_config_proto_rawDesc), len(file_proxy_mx_config_proto_rawDesc)))
	})
	return file_proxy_mx_config_proto_rawDescData
}

var file_proxy_mx_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proxy_mx_config_proto_goTypes = []any{
	(*Cuenta)(nil),                  // 0: v2ray.core.proxy.mx.Cuenta
	(*ConfiguracionCliente)(nil),    // 1: v2ray.core.proxy.mx.ConfiguracionCliente
	(*ConfiguracionServidor)(nil),   // 2: v2ray.core.proxy.mx.ConfiguracionServidor
	(*protocol.ServerEndpoint)(nil), // 3: v2ray.core.common.protocol.ServerEndpoint
	(*protocol.User)(nil),           // 4: v2ray.core.common.protocol.User
}
var file_proxy_mx_config_proto_depIdxs = []int32{
	3, // 0: v2ray.core.proxy.mx.ConfiguracionCliente.vnext:type_name -> v2ray.core.common.protocol.ServerEndpoint
	4, // 1: v2ray.core.proxy.mx.ConfiguracionServidor.users:type_name -> v2ray.core.common.protocol.User
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_mx_config_proto_init() }
func file_proxy_mx_config_proto_init() {
	if File_proxy_mx_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_mx_config_proto_rawDesc), len(file_proxy_mx_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_mx_config_proto_goTypes,
		DependencyIndexes: file_proxy_mx_config_proto_depIdxs,
		MessageInfos:      file_proxy_mx_config_proto_msgTypes,
	}.Build()
	File_proxy_mx_config_proto = out.File
	file_proxy_mx_config_proto_goTypes = nil
	file_proxy_mx_config_proto_depIdxs = nil
}
